
name: Test build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: new pip
      run: pip3 install --user --upgrade pip &&
           export PATH="$HOME/.local/bin:$PATH"
      
    - name: Install tag plugin
      run: pip3 install setuptools
      
    - name: Install pyYAML
      run: pip3 install --ignore-installed PyYAML
    
    - name: Install MkDocs
      run: pip3 install mkdocs
    
    - name: test mkdocs
      run: $HOME/.local/bin/mkdocs --version
      
    - name: Install mkdocs dependencies
      run: pip3 install git+https://github.com/jldiaz/mkdocs-plugin-tags.git && 
           pip3 install mkdocs-material
   
    - name: build site
      run: $HOME/.local/bin/mkdocs build -s
